### ISSUE TITLE
libgcc missing run requirement on linux?

### ISSUE THREAD

**Issue by danielfrg** [conda-forge/spacy-feedstock#16]
I think `libgcc` is a missing run requirement on linux. 

I tested this on a debian docker container.

On a new miniconda installation I get this:
```
>>> import spacy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.6/site-packages/spacy/__init__.py", line 5, in <module>
    from .deprecated import resolve_model_name
  File "/opt/conda/lib/python3.6/site-packages/spacy/deprecated.py", line 8, in <module>
    from .cli import download
  File "/opt/conda/lib/python3.6/site-packages/spacy/cli/__init__.py", line 5, in <module>
    from .train import train, train_config
  File "/opt/conda/lib/python3.6/site-packages/spacy/cli/train.py", line 8, in <module>
    from ..scorer import Scorer
  File "/opt/conda/lib/python3.6/site-packages/spacy/scorer.py", line 4, in <module>
    from .gold import tags_to_entities
ImportError: libgomp.so.1: cannot open shared object file: No such file or directory
```

If I install libgcc from defaults it works:

```
root@26bbe6af725a:/work# conda install libgcc
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /opt/conda:

The following NEW packages will be INSTALLED:

    libgcc: 5.2.0-0

Proceed ([y]/n)? y

libgcc-5.2.0-0 100% |##################################################################################################################################| Time: 0:00:00   4.39 MB/s
root@26bbe6af725a:/work# python
Python 3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 12:22:00)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
>>>
```

I can submit a PR to fix this but I wanted to know if there is something I am missing.

**Comment by rmax** [comment]
Yes, I think you are right. We need to add `gcc` as build requirement and `libgcc` as run requirement for `linux`. Please go ahead and make the PR.
